database:
  host: "127.0.0.1"
  port: "3306"
  database: "database"
  username: "username"
  password: "password"
redis:
  host: "127.0.0.1"
  port: "6379"
  database: 0
  password: "password"
memoryfixer:
  needed: false
  min: 1024
chat:
  needed: false
  announce_vip_join: false