chat:
  channels:
    local:
      tag: L
      format: "&e[L] %Group%%ClanTag%%Rank%&f%PlayerName%: &e"
      distance: 150
      multi-world: false
      min-price: 0.0
    global:
      tag: G
      format: "&7[G] %Group%%ClanTag%%Rank%&f%PlayerName%: &7"
      distance: -1
      multi-world: true
      min-price: 1000.0
  tell-min-price: 1000.0
  default-channel: L
kits: {}
spawn: "world,0,0,0,0,0"
drops:
  group-boost:
    ALL: 0.0
    VIP: 5.0
    VIP_PLUS: 10.0
    MVP: 15.0
    MVP_PLUS: 20.0
  price:
    efficiency-upgrade: 1000.0
    unbreaking-upgrade: 3000.0
    fortune-upgrade: 5000.0
    silktouch-upgrade: 5000.0
    explosion-upgrade: 10000.0
    laser-upgrade: 50000.0
    nuke-upgrade: 100000.0
    weasel-upgrade: 50000.0
  farm:
    worlds:
      - "Plotworld"
    wheat:
      enabled: true
      replant-fully-grown-only: true
    reeds:
      enabled: true
    netherwart:
      enabled: true
      replant-fully-grown-only: true
    cocoa-beans:
      enabled: true
      replant-fully-grown-only: true
    carrots:
      enabled: true
      replant-fully-grown-only: true
    potatoes:
      enabled: true
      replant-fully-grown-only: true
    pumpkin:
      enabled: true
      replant-fully-grown-only: true
    melon:
      enabled: true
      replant-fully-grown-only: true
  menus:
    drops:
      name: "&3&lDrops"
      size: 54
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,52:0,1,true,sell-mobs,&a&lSell Mobs,&7Quantity: &6%DropsQuantity%\n&7Sell By: &a%SellPrice% &7(&a+ &2%BoostPrice%&7)\n&7Boost: &f%BoostPercentage%%"
        - "11,160:15,1,false,,&l,"
        - "12,56:0,1,true,sell-ores,&a&lSell Ores,&7Quantity: &6%DropsQuantity%\n&7Sell By: &a%SellPrice% &7(&a+ &2%BoostPrice%&7)\n&7Boost: &f%BoostPercentage%%"
        - "13,160:15,1,false,,&l,"
        - "14,372:0,1,true,sell-drops,&a&lSell Drops,&7Quantity: &6%DropsQuantity%\n&7Sell By: &a%SellPrice% &7(&a+ &2%BoostPrice%&7)\n&7Boost: &f%BoostPercentage%%"
        - "15,160:15,1,false,,&l,"
        - "16,296:0,1,true,sell-farms,&a&lSell Farms,&7Quantity: &6%DropsQuantity%\n&7Sell By: &a%SellPrice% &7(&a+ &2%BoostPrice%&7)\n&7Boost: &f%BoostPercentage%%"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:15,1,false,,&l,"
        - "27,160:15,1,false,,&l,"
        - "28,388:0,1,true,sell-all,&b&lSell All,&7Quantity: &6%DropsQuantity%\n&7Sell By: &a%SellPrice% &7(&a+ &2%BoostPrice%&7)\n&7Boost: &f%BoostPercentage%%"
        - "29,160:15,1,false,,&l,"
        - "30,160:15,1,false,,&l,"
        - "31,160:14,1,true,auto-sell,&b&lAuto Sell,&7Click to &aenable &7or &cdisable &7auto sell."
        - "32,160:15,1,false,,&l,"
        - "33,160:15,1,false,,&l,"
        - "34,377:0,1,true,booster,&b&lBooster,&7Rank Boost: &f%RankBoost%%\n&7Vip Boost: &f%GroupBoost%%\n&7Total: &a%BoostPercentage%%"
        - "35,160:15,1,false,,&l,"
        - "36,160:15,1,false,,&l,"
        - "37,160:15,1,false,,&l,"
        - "38,160:15,1,false,,&l,"
        - "39,160:15,1,false,,&l,"
        - "40,160:15,1,false,,&l,"
        - "41,160:15,1,false,,&l,"
        - "42,160:15,1,false,,&l,"
        - "43,160:15,1,false,,&l,"
        - "44,160:15,1,false,,&l,"
        - "45,160:15,1,false,,&l,"
        - "46,160:15,1,false,,&l,"
        - "47,160:15,1,false,,&l,"
        - "48,160:15,1,false,,&l,"
        - "49,160:15,1,false,,&l,"
        - "50,160:15,1,false,,&l,"
        - "51,160:15,1,false,,&l,"
        - "52,160:15,1,false,,&l,"
        - "53,160:15,1,false,,&l,"
    upgrade:
      name: "&b&lPickaxe Upgrader"
      size: 54
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,278:0,1,true,upgrade-efficiency,&a&lUpgrade Eficiency,&7From Level: &6&l%CurrentLevel%\n&7To Level: &b&l%NextLevel%\n&7Price: &a&l%Price%"
        - "11,160:15,1,false,,&l,"
        - "12,145:0,1,true,upgrade-unbreaking,&b&lUpgrade Unbreaking,&7From Level: &6&l%CurrentLevel%\n&7To Level: &b&l%NextLevel%\n&7Price: &a&l%Price%"
        - "13,160:15,1,false,,&l,"
        - "14,264:0,1,true,upgrade-fortune,&d&lUpgrade Fortune,&7From Level: &6&l%CurrentLevel%\n&7To Level: &b&l%NextLevel%\n&7Price: &a&l%Price%"
        - "15,160:15,1,false,,&l,"
        - "16,1:0,1,true,upgrade-silktouch,&e&lUpgrade Silk Touch,&7From Level: &6&l%CurrentLevel%\n&7To Level: &b&l%NextLevel%\n&7Price: &a&l%Price%"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:15,1,false,,&l,"
        - "27,160:15,1,false,,&l,"
        - "28,46:0,1,true,upgrade-explosion,&c&lUpgrade Explosion,&7From Level: &6&l%CurrentLevel%\n&7To Level: &b&l%NextLevel%\n&7Price: &a&l%Price%"
        - "29,160:15,1,false,,&l,"
        - "30,369:0,1,true,upgrade-laser,&6&lUpgrade Laser,&7From Level: &6&l%CurrentLevel%\n&7To Level: &b&l%NextLevel%\n&7Price: &a&l%Price%"
        - "31,160:15,1,false,,&l,"
        - "32,152:0,1,true,upgrade-nuke,&8&l&k|||&4&lUpgrade Nuke&8&l&k|||,&7From Level: &6&l%CurrentLevel%\n&7To Level: &b&l%NextLevel%\n&7Price: &a&l%Price%"
        - "33,160:15,1,false,,&l,"
        - "34,381:0,1,true,upgrade-weasel,&7&lUpgrade Weasel,&7From Level: &6&l%CurrentLevel%\n&7To Level: &b&l%NextLevel%\n&7Price: &a&l%Price%"
        - "35,160:15,1,false,,&l,"
        - "36,160:15,1,false,,&l,"
        - "37,160:15,1,false,,&l,"
        - "38,160:15,1,false,,&l,"
        - "39,160:15,1,false,,&l,"
        - "40,160:15,1,false,,&l,"
        - "41,160:15,1,false,,&l,"
        - "42,160:15,1,false,,&l,"
        - "43,160:15,1,false,,&l,"
        - "44,160:15,1,false,,&l,"
        - "45,160:15,1,false,,&l,"
        - "46,160:15,1,false,,&l,"
        - "47,160:15,1,false,,&l,"
        - "48,160:15,1,false,,&l,"
        - "49,160:15,1,false,,&l,"
        - "50,160:15,1,false,,&l,"
        - "51,160:15,1,false,,&l,"
        - "52,160:15,1,false,,&l,"
        - "53,160:15,1,false,,&l,"
tab:
  header: "&a&lFightCraft\n&2&lSecond Line"
  footer: "&b&lhttp://fightcraft.com.br/\n&2&lSecond Line"
warp:
  rank-delay:
    ALL: 5
  warps: {}
mine-reseter:
  enabled: true
  alert-times:
    - 180
    - 120
    - 60
    - 30
    - 10
    - 5
    - 4
    - 3
    - 2
    - 1
  mines: {}
rankup:
  default-rank: "Slave"
  ranks:
    0:
      name: "Slave"
      cost: 1000.0
      can-level-up: true
      display-name: "&7Slave"
      ores: 1000.0
      boost: 0.0
      color: "&7"
    1:
      name: "Merchant"
      cost: 10000.0
      can-level-up: true
      display-name: "&bMerchant"
      ores: 1000.0
      boost: 1.0
      color: "&b"
    2:
      name: "God"
      cost: 100000.0
      can-level-up: false
      display-name: "&aGod"
      ores: 1000.0
      boost: 5.0
      color: "&a"
clans:
  create-price: 1000.0
  civilian-kill-weight: 0.5
  neutral-kill-weight: 1.0
  rival-kill-weight: 2.0
  invite-expiration: 3
crates:
  menus:
    main:
      name: "&2&lOpening %CrateName%"
      size: 27
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:15,1,false,,&l,"
machines:
  fuel:
    id: "263:1"
    name: "&a&lFuel"
    lore:
      - "&aLiters: &6%liters%"
      - "&aBoost: &6%boost%"
  types:
    Type1:
      name: "&a&lType1"
      item:
        id: "1:0"
        name: "&a&lMachine 1"
        lore:
          - "&7Curent: &a%amount%"
      drop:
        id: "372:0"
        name: "&a&lDrop Type1"
        price: 100.00
        lore:
          - "&7Curent: &a%amount%"
      levels:
        0:
          drop-delay: 10
          drop-quantity: 1
          max-tank: 100
          max-drop-count: 60
          upgrade-cost: 1000.0
        1:
          drop-delay: 8
          drop-quantity: 2
          max-tank: 200
          max-drop-count: 120
          upgrade-cost: 2000.0
        2:
          drop-delay: 6
          drop-quantity: 3
          max-tank: 300
          max-drop-count: 240
          upgrade-cost: 4000.0
        3:
          drop-delay: 4
          drop-quantity: 4
          max-tank: 400
          max-drop-count: 480
          upgrade-cost: 8000.0
        4:
          drop-delay: 2
          drop-quantity: 5
          max-tank: 500
          max-drop-count: 960
          upgrade-cost: 10000.0
  menus:
    main:
      name: "&a&lMachines Menu"
      size: 27
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,138:0,1,true,open machines,&a&lYour Machines,"
        - "11,160:15,1,false,,&l,"
        - "12,388:0,1,true,open shop,&b&lMachine Shop,"
        - "13,160:15,1,false,,&l,"
        - "14,386:0,1,true,open permissions,&6&lFriends Permissions,"
        - "15,160:15,1,false,,&l,"
        - "16,120:0,1,true,open friends,&7&lYour Friends,"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:15,1,false,,&l,"
    shop:
      name: "&a&lMachines Shop"
      size: 54
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,160:15,1,false,,&l,"
        - "11,160:15,1,false,,&l,"
        - "12,160:15,1,false,,&l,"
        - "13,160:15,1,false,,&l,"
        - "14,138:0,1,true,buymachine Type1 8000.00,&a&lMachine 1,"
        - "15,263:0,1,true,buyfuel 5 1 0 8000.00,&b&lFuel 1,"
        - "16,263:0,1,true,buyfuel 100 10 0 8000.00,&b&lFuel 2,"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:15,1,false,,&l,"
        - "27,160:15,1,false,,&l,"
        - "28,160:15,1,false,,&l,"
        - "29,160:15,1,false,,&l,"
        - "30,160:15,1,false,,&l,"
        - "31,160:15,1,false,,&l,"
        - "32,160:15,1,false,,&l,"
        - "33,160:15,1,false,,&l,"
        - "34,160:15,1,false,,&l,"
        - "35,160:15,1,false,,&l,"
        - "36,160:15,1,false,,&l,"
        - "37,160:15,1,false,,&l,"
        - "38,160:15,1,false,,&l,"
        - "39,160:15,1,false,,&l,"
        - "40,160:15,1,false,,&l,"
        - "41,160:15,1,false,,&l,"
        - "42,160:15,1,false,,&l,"
        - "43,160:15,1,false,,&l,"
        - "44,160:15,1,false,,&l,"
        - "45,160:15,1,false,,&l,"
        - "46,160:15,1,false,,&l,"
        - "47,160:15,1,false,,&l,"
        - "48,160:15,1,false,,&l,"
        - "49,160:15,1,false,,&l,"
        - "50,160:15,1,false,,&l,"
        - "51,160:15,1,false,,&l,"
        - "52,160:15,1,false,,&l,"
        - "53,160:14,1,true,open main,&4&lGo Back,"
    machines:
      name: "&a&lYour Machines"
      size: 27
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,160:8,1,true,emptyslot,&6&lEmpty Slot,"
        - "11,160:8,1,true,emptyslot,&6&lEmpty Slot,"
        - "12,160:8,1,true,emptyslot,&6&lEmpty Slot,"
        - "13,160:8,1,true,emptyslot,&6&lEmpty Slot,"
        - "14,160:8,1,true,emptyslot,&6&lEmpty Slot,"
        - "15,160:8,1,true,emptyslot,&6&lEmpty Slot,"
        - "16,160:8,1,true,emptyslot,&6&lEmpty Slot,"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:14,1,true,open main,&4&lGo Back,"
    machine:
      name: "&a&lMachine %MachineName%"
      size: 27
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,340:0,1,true,,&a&lMachine Info,&bLevel: %MachineLevel%/5\n&bDrops: %MachineDrops%/%MachineMaxDropCount%\n&bFuel: %MachineFuel%/%MachineMaxFuel%\n&bDrop Quantity: %MachineDropQuantity%\n&bDrop Delay: %MachineDropDelay%"
        - "11,160:15,1,false,,&l,"
        - "12,399:0,1,true,upgrademachine,&b&lUpgrade Machine,&bLevel: %MachineLevel%/5\n&bCost: $%MachineUpgradeCost%\n&6&lClick to upgrade!"
        - "13,160:15,1,false,,&l,"
        - "14,263:1,1,true,open fuel,&6&lFuel,&bFuel: %MachineFuel%/%MachineMaxFuel%"
        - "15,160:15,1,false,,&l,"
        - "16,372:0,1,true,open drops,&9&lDrops,&bDrops: %MachineDrops%/%MachineMaxDropCount%"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:14,1,true,open machines,&4&lGo Back,"
    fuel:
      name: "%MachineName% Fuel"
      size: 27
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,160:7,1,true,percentageslot,&a&lFuel: &6&l%FuelConsuption%%,"
        - "11,160:7,1,true,percentageslot,&a&lFuel: &6&l%FuelConsuption%%,"
        - "12,160:7,1,true,percentageslot,&a&lFuel: &6&l%FuelConsuption%%,"
        - "13,160:7,1,true,percentageslot,&a&lFuel: &6&l%FuelConsuption%%,"
        - "14,160:7,1,true,percentageslot,&a&lFuel: &6&l%FuelConsuption%%,"
        - "15,160:7,1,true,percentageslot,&a&lFuel: &6&l%FuelConsuption%%,"
        - "16,160:7,1,true,percentageslot,&a&lFuel: &6&l%FuelConsuption%%,"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:14,1,true,open machine,&4&lGo Back,"
    drops:
      name: "%MachineName% Drops"
      size: 27
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,160:8,1,true,dropslot,&a&lDrops Fill: &6&l%DropFill%%,"
        - "11,160:8,1,true,dropslot,&a&lDrops Fill: &6&l%DropFill%%,"
        - "12,160:8,1,true,dropslot,&a&lDrops Fill: &6&l%DropFill%%,"
        - "13,160:8,1,true,dropslot,&a&lDrops Fill: &6&l%DropFill%%,"
        - "14,160:8,1,true,dropslot,&a&lDrops Fill: &6&l%DropFill%%,"
        - "15,160:8,1,true,dropslot,&a&lDrops Fill: &6&l%DropFill%%,"
        - "16,160:8,1,true,dropslot,&a&lDrops Fill: &6&l%DropFill%%,"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:14,1,true,open machine,&4&lGo Back,"