database:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "default"
redis:
  host: "127.0.0.1"
  port: "6379"
  database: 0
  password: null
memoryfixer:
  needed: false
  min: 1024
chat:
  needed: false
  announce_vip_join: false
languages:
  - "en_US.json"