mine-reseter:
  enabled: true
  alert-times:
    - 180
    - 120
    - 60
    - 30
    - 10
    - 5
    - 4
    - 3
    - 2
    - 1
  mines:
    0:
      name: "Mina 1"
      enabled: true
      alert-area: 200
      point1: "world,-3,0,3,0,0"
      point2: "world,-32,20,26,0,0"
      delay: 60
      ores:
        - "0.5,1:0"
        - "0.5,3:0"
machines:
  fuel:
    id: "163:1"
    name: "&a&lFuel"
    lore:
      - "&7Liters: &a%liters%"
  types:
    Type1:
      name: "Type1"
      price: 8000.00
      item:
        id: "1:0"
        name: "&a&lMachine 1"
        lore:
          - "&7Curent: &a%amount%"
          - "&7Sell price: &a$%price%"
          - ""
          - "&7Click to sell!"
      drop:
        id: "151:1"
        name: "&a&lDrop Type1"
        price: 1000.00
        lore:
          - "&7Curent: &a%amount%"
          - "&7Sell price: &a$%price%"
          - ""
          - "&7Click to sell!"
      levels:
        0:
          delay: 10
          quantity: 1
        1:
          delay: 8
          quantity: 2
        2:
          delay: 6
          quantity: 3
        3:
          delay: 4
          quantity: 4
        4:
          delay: 2
          quantity: 5
  menus:
    main:
      name: "&a&lMachines Menu"
      size: 27
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,138:0,1,true,open machines,&a&lYour Machines,"
        - "11,160:15,1,false,,&l,"
        - "12,388:0,1,true,open shop,&b&lMachine Shop,"
        - "13,160:15,1,false,,&l,"
        - "14,386:0,1,true,open permissions,&6&lFriends Permissions,"
        - "15,160:15,1,false,,&l,"
        - "16,120:0,1,true,open friends,&7&lYour Friends,"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:15,1,false,,&l,"
    shop:
      name: "&a&lMachines Shop"
      size: 54
      items:
        - "0,160:15,1,false,,&l,"
        - "1,160:15,1,false,,&l,"
        - "2,160:15,1,false,,&l,"
        - "3,160:15,1,false,,&l,"
        - "4,160:15,1,false,,&l,"
        - "5,160:15,1,false,,&l,"
        - "6,160:15,1,false,,&l,"
        - "7,160:15,1,false,,&l,"
        - "8,160:15,1,false,,&l,"
        - "9,160:15,1,false,,&l,"
        - "10,160:15,1,false,,&l,"
        - "11,160:15,1,false,,&l,"
        - "12,160:15,1,false,,&l,"
        - "13,160:15,1,false,,&l,"
        - "14,160:15,1,false,,&l,"
        - "15,160:15,1,false,,&l,"
        - "16,160:15,1,false,,&l,"
        - "17,160:15,1,false,,&l,"
        - "18,160:15,1,false,,&l,"
        - "19,160:15,1,false,,&l,"
        - "20,160:15,1,false,,&l,"
        - "21,160:15,1,false,,&l,"
        - "22,160:15,1,false,,&l,"
        - "23,160:15,1,false,,&l,"
        - "24,160:15,1,false,,&l,"
        - "25,160:15,1,false,,&l,"
        - "26,160:15,1,false,,&l,"
        - "27,160:15,1,false,,&l,"
        - "28,160:15,1,false,,&l,"
        - "29,160:15,1,false,,&l,"
        - "30,160:15,1,false,,&l,"
        - "31,160:15,1,false,,&l,"
        - "32,160:15,1,false,,&l,"
        - "33,160:15,1,false,,&l,"
        - "34,160:15,1,false,,&l,"
        - "35,160:15,1,false,,&l,"
        - "36,160:15,1,false,,&l,"
        - "37,160:15,1,false,,&l,"
        - "38,160:15,1,false,,&l,"
        - "39,160:15,1,false,,&l,"
        - "40,160:15,1,false,,&l,"
        - "41,160:15,1,false,,&l,"
        - "42,160:15,1,false,,&l,"
        - "43,160:15,1,false,,&l,"
        - "44,160:15,1,false,,&l,"
        - "45,160:15,1,false,,&l,"
        - "46,160:15,1,false,,&l,"
        - "47,160:15,1,false,,&l,"
        - "48,160:15,1,false,,&l,"
        - "49,160:15,1,false,,&l,"
        - "50,160:15,1,false,,&l,"
        - "51,160:15,1,false,,&l,"
        - "52,160:15,1,false,,&l,"
        - "53,160:14,1,true,open main,&4&lGo Back,"