mine-reseter:
  enabled: true
  alert-times:
    - 180
    - 120
    - 60
    - 30
    - 10
    - 5
    - 4
    - 3
    - 2
    - 1
  mines:
    0:
      name: "Mina 1"
      enabled: true
      alert-area: 200
      point1: "world,-3,0,3,0,0"
      point2: "world,-32,20,26,0,0"
      delay: 60
      ores:
        - "0.5,1:0"
        - "0.5,3:0"
machines:
  types:
    0:
      name: "Type1"
      drop: "351:1;"
      levels:
        0:
          delay: 10
          quantity: 1
        1:
          delay: 8
          quantity: 2
        2:
          delay: 6
          quantity: 3
        3:
          delay: 4
          quantity: 4
        4:
          delay: 2
          quantity: 5
